name: flutter_wordpress_app
description: Flutter news app for wordpress platform

version: 2.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.11
  http: ^0.13.3
  html: ^0.15.0
  flutter_html: ^2.1.2
  dio: ^4.0.0
  loading: ^1.0.2
  intl: ^0.17.0
  share: ^2.0.4
  path_provider: ^2.0.5
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.8
  flutter_widget_from_html: ^0.7.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_messaging_web: ^2.2.5
  alice: ^0.2.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher"
  ios: true
  image_path: assets/launcher.png

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/no-internet.png
    - assets/play-button.png
    - assets/boxed/fashion.png
    - assets/boxed/health.png
    - assets/boxed/lifestyle.png
    - assets/boxed/music.png
    - assets/boxed/photography.png
    - assets/boxed/recipies.png
    - assets/boxed/sport.png
    - assets/boxed/travel.png
    - assets/boxed/world.png
    - assets/more/favourite.png
    - assets/more/contact.png
    - assets/more/share.png
    - assets/more/profile.png
    - assets/more/notification.png
    - assets/logo-unas.png
    - assets/unas.png
    - assets/campustimes.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf

    - family: Soleil
      fonts:
        - asset: fonts/Soleil/Soleil-Bold.otf
        - asset: fonts/Soleil/Soleil-Regular.otf
